### ISSUE TITLE
invite friend not working

### ISSUE THREAD

**Issue by balasaheb143** [sromku/android-simple-facebook#13]
when i invite friends it display Toast invitation was send but not display in friends notification

**Comment by deepnashi** [comment]
Hi @sromku  i used your code it is awesome but i ma facing an issue . when i log in to facebook by facebook ap it shows me an error that key hash invalid. how can i do it ?

**Comment by pulikkoden** [comment]
is it necessary to upload app on playstore to send invites to facebook friends? 
My problem is - i can send invites to friends from my android app but none of them receive it even from an android app.
