### ISSUE TITLE
Facebook SDK Error While exporting my project

### ISSUE THREAD

**Issue by AhmadHegazy** [sromku/android-simple-facebook#173]
i use adroid-simple-facebook, While i try to export my project i have error in FaceBookSDK
in FacebookFragment(This fragment class should be public) & alson in FriendPickerFragment  & PlacePickerFragment (Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) 
 instead) and in ToolTipPopup (Suspicious method call; should probably call "measure" rather than "onMeasure")

**Comment by ghost** [comment]
Thank you very much
