### ISSUE TITLE
Publish story with create new object

### ISSUE THREAD

**Issue by Armeriol** [sromku/android-simple-facebook#182]
Hi,

I want to publish story with upload it to facebook servers. I read that I need to use create(StoryObject, OnCreateStoryObject) and I did it. In result I get some number string that is showing in TextView in fragment. I dont get any error and everything looks ok but when I log in my account I dont see my story. Can you provide example of creating story and upload it to facebook servers like you did with "Upload story meta tags to your private servers."? Is this possible to upload my own picture from android device with my story?

**Comment by jachanaka** [comment]
hi,

what is mean by bellow sout,

I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false

please help.

**Comment by Grishman** [comment]
Tell me pls, you can create Story from my android app only if i logged in facebook in my app? because i get an error that "You are not logged in" in .create() method
