### ISSUE TITLE
App closing on start

### ISSUE THREAD

**Issue by Pitu** [sromku/android-simple-facebook#196]
Hi there, after following  the instructions on how to set up Simple Facebook, I'm facing this error on logcat whenever I try to start the app.

07-08 19:08:34.363: E/AndroidRuntime(15299): java.lang.NoClassDefFoundError: com.facebook.internal.SessionAuthorizationType
07-08 19:08:34.363: E/AndroidRuntime(15299):    at com.sromku.simple.fb.Permission$Type.<clinit>(Permission.java:55)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at com.sromku.simple.fb.Permission.<clinit>(Permission.java:14)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at com.moshimoshistudios.whonder.LoginActivity.<init>(LoginActivity.java:25)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at java.lang.Class.newInstanceImpl(Native Method)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at java.lang.Class.newInstance(Class.java:1208)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2222)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.ActivityThread.access$900(ActivityThread.java:161)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.os.Handler.dispatchMessage(Handler.java:102)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.os.Looper.loop(Looper.java:157)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at android.app.ActivityThread.main(ActivityThread.java:5356)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at java.lang.reflect.Method.invokeNative(Native Method)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at java.lang.reflect.Method.invoke(Method.java:515)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-08 19:08:34.363: E/AndroidRuntime(15299):    at dalvik.system.NativeStart.main(Native Method)

LoginActivity.java:25 is this chunk:
Permission[] permissions = new Permission[] {
            Permission.USER_PHOTOS, //THIS IS LINE 25
            Permission.EMAIL,
            Permission.PUBLISH_ACTION
        };

I hope someone can help me out here, thanks!

**Comment by GelaniNijraj** [comment]
@sromku I'm getting a similar error and I've already added `compile 'com.facebook.android:facebook-android-sdk:4.10.0'` in my `build.gradle`. Can you help me with that?
