### ISSUE TITLE
Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by achinverma** [sromku/android-simple-facebook#214]
[2014-08-11 12:28:54 - Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536
[2014-08-11 12:28:54 - TheGrooveboss] Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536

got this error when i import this ? how to fix this error?

**Comment by tany123** [comment]
Got this same issue for my project when i import new google play services
After doing some research to work with eclipse found one solution


5
down vote
Ideally you should use ProGurad, however you can follow these two steps:

Step 1: Remove unused classes from jar file

Open the google-play-services.jar in the library project with a zip file manager such as Winrar or 7zip. You will find many folder such as maps, games, just delete the ones you don't need. Make sure you keep common, dynamic, internal .

Step 2: Remove unused resource from res folder

Most of the resources in the google-play-services_lib\res folder might be of no use so you can remove it. These include values-af, values-am, .... what you need to keep is color, drawable, drawable-hdpi and values folder.

Refresh and build the google-play-services_lib project and your project. Your apk size should be decreased.


http://stackoverflow.com/questions/26506557/how-to-customize-google-play-services-to-decrease-jar-size
Just delete non usable packages from google-play-services.jar manually 
It works for me

**Comment by Tolsi** [comment]
@tany123 all you have listed is terrible practices, because there are special tools and proven solutions described above. Recently appeared [Multidex](https://developer.android.com/tools/building/multidex.html)
