### ISSUE TITLE
How can I get User Email?

### ISSUE THREAD

**Issue by Samsu7609** [sromku/android-simple-facebook#220]
Step 1 : Here is my permission

Permission[] permissions = new Permission[] { 
                Permission.PUBLIC_PROFILE, 
                Permission.EMAIL,
};

Step 2 : request permission:

private OnNewPermissionsListener onNewPermissionsListener = new OnNewPermissionsListener() {

```
        @Override
        public void onSuccess(String accessToken) {
            Log.e("SIMPLE", "onSuccess ");

            mSimpleFacebook.getSession().refreshPermissions();


            Profile.Properties properties = new Profile.Properties.Builder()
            .add(Profile.Properties.EMAIL)
            .build();

            // do the get profile action
            mSimpleFacebook.getProfile(properties, onProfileRequestListener);

        }
```

};

 i got OnNewPermissionsListener.onSuccess() , but i still can't get user email....
 and i use this method to check permission 
 mSimpleFacebook.getSession().getDeclinedPermissions() --> email

 i need to get user Email at runtime   ...
 if anyone know how to solve this problem
 plz shared some information 

Thanks

**Comment by walaagomaa18** [comment]
i does not working for me any help?
