### ISSUE TITLE
Getting permission errors when publishing feed with dialog

### ISSUE THREAD

**Issue by raylee4204** [sromku/android-simple-facebook#234]
Publishing feed with dialog shouldn't require publish_actions permission.
However, if I don't have the publish permission, I still get errors for this in a publish callback such as "Canceled by user" or "'[publish_actions]' weren't accepted by user"

**Comment by aliumujib** [comment]
I still am getting this issue when publishing without dialog and the library tries to get read permissions from facebook automatically. is it supposed to behave like that??
