### ISSUE TITLE
Posting to page owned by user

### ISSUE THREAD

**Issue by rajeefmk** [sromku/android-simple-facebook#315]
Is the functionality implemented in the library ? If yes, could you please point to the corresponding documentation ?

**Comment by sromku** [comment]
Sorry for super late response, but the answer is yes and this option exist for a long time. It looks that I missed to add this option to wiki page, and this to be updated. 

The method in `SimpleFacebook`: 
``` java  
public void publish(String entityId, Feed feed, OnPublishListener onPublishListener) 
```

The `entityId` can be one of follows:

- Group
- Event
- Page

Please note that publishing on page you have to be an admin and you need `MANAGE_PAGES` permission accepted in addition to `PUBLISH_ACTION`

Best,
Roman
