### ISSUE TITLE
com.facebook.FacebookAuthorizationException: UnknownError: The proxied app cannot request publish permissions without having being installed previously. (410)

### ISSUE THREAD

**Issue by hdbd789** [sromku/android-simple-facebook#316]
Permission[] permissions = new Permission[] {
                Permission.PUBLIC_PROFILE,
                Permission.PUBLISH_ACTION,
        };

        SimpleFacebookConfiguration configuration = new SimpleFacebookConfiguration.Builder()
                .setAppId(APP_ID)
                .setNamespace(APP_NAMESPACE)
                .setPermissions(permissions)
                .setDefaultAudience(SessionDefaultAudience.FRIENDS)
                .setAskForAllPermissionsAtOnce(false)
                .build();

        SimpleFacebook.setConfiguration(configuration);

**Comment by hdbd789** [comment]
please help me

**Comment by LeDam** [comment]
Same problem here.

**Comment by sromku** [comment]
@hdbd789 @LeDam Please check latest release: https://github.com/sromku/android-simple-facebook#latest-release. In general this exception can happen on facebook side, if you try to ask for publish permissions before accepting at least one read permission. With this lib it shouldn't happen, but still. Please try latest library version. It has many updates to support latest facebook sdk 4.2+. If you still get the error please reopen the ticket and let me know. 
Best, Roman
