### ISSUE TITLE
Without facebook app same user login if user logged out into 

### ISSUE THREAD

**Issue by neel7892** [sromku/android-simple-facebook#319]
first time signing out from the account and after that pressing facebook sign in button, It displays previously logged account details it does not displays facebook sign in page. Without facebbok apk installed.. What is solution for that ??????

**Comment by sromku** [comment]
@neel7892 grab the latest build release. It supports maven and latest facebook sdk (4.2+). https://github.com/sromku/android-simple-facebook#latest-release. Now, if you logout and then login, you will be asked again to put the username and password again as expected. Of course, if the facebook native app isn't installed.
