### ISSUE TITLE
Memory leak after clean()

### ISSUE THREAD

**Issue by xbezdeka** [sromku/android-simple-facebook#320]
SimpleFacebook creates a memory leak even after clean() is called.
In your clean() method you're calling:

SessionManager.activity = null;

but SessionManager contains also UiLifecycleHelper which is referencing activity as well, so you need to clear that one too

**Comment by morgotth** [comment]
+1, this is a serious issue. I hope that will be fixed soon.

**Comment by sromku** [comment]
Thanks @xbezdeka @morgotth ! Right, fixed. Please check the latest version. Now, the lib holds a weak reference to `Activity` and won't prevent from GC to clean `Activity`. And, the `UiLifecycleHelper` is no more in use.
Also, the lib is updated (finally) to support latest facebook sdk (4.2+) and has much better maven support. 
``` gradle
dependencies {
    compile 'com.sromku:simple-fb:4.0.2'
}
```
And thanks again!
