### ISSUE TITLE
Your library is not working!

### ISSUE THREAD

**Issue by shaibenshim** [sromku/android-simple-facebook#324]

**Comment by stezo** [comment]
Seriously? You are a developer and think that 'your library is not working' is helpful?
Then I will tell you something which is at least as helpful as your message: The library is working.

**Comment by sromku** [comment]
The library will be updated soon to support latest facebook sdk 4.+ changes. But, yes, as @stezo said, it works fine. @shaibenshim please explain what have you tried and how can I support your issues.

**Comment by konigsoft** [comment]
@sromku nice to you see and the great new related to the update to support facebook sdk4+.
@shaibenshim if you explain what is not working i m pretty sure that you will have help.
the number of star and fork at least presume that it working and yes it is working

**Comment by sromku** [comment]
@shaibenshim , @stezo , @konigsoft . New version that supports latest facebook SDK (4.2+) was released :). There is a maven support and you can easily use this lib. You can find it here: https://github.com/sromku/android-simple-facebook#latest-release
``` gradle
dependencies {
    compile 'com.sromku:simple-fb:4.0.2'
}
```
Best, Roman
