### ISSUE TITLE
Simple Facebook repo will not import as a new module

### ISSUE THREAD

**Issue by noni-mizu** [sromku/android-simple-facebook#326]
I am trying to simply import Simple Facebook as a new module into my existing app project in Android Studio, and I get the error message: " Select a module to import", but I have selected the folder Simple Facebook, so I don't know what it wants.

I then tried to select the entire repo download, android-simple-facebook-master, as it has some gradle files as well as the Simple Facebook Sample, but then it says it is already in my project (which it is not, not visible in the Project structure, and not in the settings.gradle file). I tried to "invalidate and restart" but that did not help. It still thinks it's in my project.

Is anyone answering these issues anymore? I'd appreciate some help, the regular Facebook SDK is not working for me either and this is my last resort. Plus it sounds so great, so I was looking forward to using it. Thank you.

**Comment by sromku** [comment]
@noni-mizu sorry for late response. These I'm days working hard to update the lib to support latest facebook sdk (4.2+). And, also gradle support for better android studio integration. The current developed branch is `v4.0-dev`. It already has all functionality working + sample app: https://github.com/sromku/android-simple-facebook/tree/v4.0-dev
In the next few days I will merge that branch into master and then you can add it without any problems. 

I'll keep you updated.

**Comment by sromku** [comment]
New version that supports latest facebook SDK (4.2+) was released. There is a maven support and you can easily use this lib. You can find it here: https://github.com/sromku/android-simple-facebook#latest-release
``` gradle
dependencies {
    compile 'com.sromku:simple-fb:4.0.2'
}
```
Best, Roman
