### ISSUE TITLE
OnNewPermissionsListener is not fired

### ISSUE THREAD

**Issue by vedi** [sromku/android-simple-facebook#327]
In `OnLoginListener` I need to call `getProfile`, but before that I need to request additional permissions to get birthday. When I call `requestNewPermissions`, I see confirmation dialog from FB, that permissions are already granted, and I press the button to close it. After that no methods of `OnNewPermissionsListener` are called. 
What can be an issue?

P.S. This example works on the branch `v4.0-dev`, but I had the same issue in the stable branch.

![screen shot 2015-06-16 at 12 25 19](https://cloud.githubusercontent.com/assets/433620/8180000/79d2a50e-1423-11e5-93ba-bbe9e3742305.png)

**Comment by sromku** [comment]
@vedi mm, interesting. I couldn't reproduce this issue and tried many possible options. In all tests, I got callback response. But before digging into this case, can you please grab the latest `v4.0-dev` branch commits and check the same scenario.

The changes are:

1. In the previous version, anytime you ask for new permissions, it will ask for all permissions that wasn't accepted before that are defined in `SimpleFacebookConfiguration` + new permissions you just asked. This was changed, and now it asks only for only those permissions that you asked upon calling to `requestNewPermissions` method.
2. Now, any public action that will try to publish `Publishable` will retrieve the required permission from `Publishable` itself and ask automatically if this permission is missing. So, this is exactly meets facebook policies where permissions to be asked with the first time user makes the action. (https://github.com/sromku/android-simple-facebook/commit/f0d6afb7b2bcfb4726e76dd63e2ae33094989a91#diff-12ce00b02843216f98502ee230512bf1R101)

Let me know if you still experience the issue.

**Comment by vedi** [comment]
@sromku, I updated the code, unfortunately it did not help. 

It's great you implemented the functionality to request additional permissions if they are needed. And I tried to change my code to use it. 
* I log in to FB (`SimpleFacebook.getInstance().login`):
  1. I see the FB dialog, get authenticated there,
  1. see the dialog from FB to provide access to the app to my profile, without publishing, confirm it,
  1. get success callback `onLogin`

* After that I try to publish (`SimpleFacebook.getInstance().publish`):
  1. see the dialog that I already granted permissions to the app (**what's definitely wrong**)
  1. press ok button, and get breakpoint at `onCancel` (https://github.com/sromku/android-simple-facebook/blob/v4.0-dev/library/src/main/java/com/sromku/simple/fb/SessionManager.java#L66), and after that at `OnPublishListener::onFail`

P.S. I do not have FB App installed on the device.

**Comment by sromku** [comment]
@vedi thanks for detailed explanation. I think the fact that you don't have the fb installed on the device makes the difference. I will check it now and get back to you.

**Comment by vedi** [comment]
@sromku, thank you, looking forward to your feedback

**Comment by sromku** [comment]
@vedi these are my steps and I've to say that everything worked as expected:
Start point:
1. The native Facebook app isn't installed on my device
2. The app that is on developer account was 'nullified'. By opening: https://www.facebook.com/settings?tab=applications and removing the app. 
3. I use sample app

The tests:
1. Opened the sample app and pressed Login button. Accepted only basic `public_profile` permission. The dialog was opened and after accepting closed and the app was logged in. `PASSED`.
2. Pressed on `Publish Feed` without dialog and the dialog with `publish_action` permission was shown. I accepted and after that the post was published successfully. `PASSED`
3. Requested for new permission in runtime 'user_groups' and then pressed on 'Get Groups', I saw the results. `PASSED`

So from what I saw, both login, publishing and requesting new permissions worked as expected.
Can you please verify and correct me if I missed something of what exactly doesn't work for you.
Much thanks @vedi !

**Comment by vedi** [comment]
@sromku, you lead me to the brilliant idea to test with your sample app, and I did that.

I used `master` (I see you merged v4 branch), only things I changed:
1. android SDK 21 changed to 22.
2. changed app_name, app_id.

And your tests:

1. Opened the sample app and pressed Login button. Accepted only basic public_profile permission. The dialog was opened and after accepting closed and the app was logged in. `PASSED`.
2. Pressed on Publish Feed without dialog and the dialog with publish_action permission was shown. I accepted and after that the post was published successfully. `FAILED` (see screenshot)
3. Requested for new permission in runtime 'user_groups' and then pressed on 'Get Groups', I saw the results. `FAILED`  (see screenshot)

![screenshot_2015-06-22-14-01-00](https://cloud.githubusercontent.com/assets/433620/8280682/454dd7d0-18e8-11e5-8107-930f6c652ef1.png)

![screenshot_2015-06-22-14-00-52](https://cloud.githubusercontent.com/assets/433620/8280717/996597ae-18e8-11e5-9172-a318c86c7142.png)

Looks like I have the same errors regardless what the app (yours or my one) I use. I'm testing on Android 4.2.1.

Do you have more ideas?

P.S. I'll get other device to check this, and come back with the results soon.

**Comment by vedi** [comment]
Android 4.1.2 and 4.4.2 - the same issues

**Comment by sromku** [comment]
@vedi interesting issue. I have tried on the same android version, with and without FB app. I changed the locale to russian just to verify that things not breaks due to localizations. And still it works like a charm. 

Few questions:
1. What is the account you login? Is it an regular user account or is it an page/app account?
2. What will happen if you delete the app from https://www.facebook.com/settings?tab=applications and re-do the same flow, just to be sure we start from clean state.

**Comment by vedi** [comment]
@sromku, thank you to reply.
1. I use my personal account to login.
2. I tried to delete the app from there, the issue is the same.

So, we have 2 possible bug-areas:
1. Simple-facebook code,
2. Something wrong with my fb app or account.

I can create apk for your app id, and you'll check it (I cannot do this). It'll allow us to exclude one of the points. What do you think?

**Comment by sromku** [comment]
The app id: 728615400528729
I have added you as a Test user.
In addition, I will make some test app that will use only pure facebook code for requesting new permissions. Will see how it goes. And yes, send me an APK if needed, I will check it. 
Much thanks.

**Comment by vedi** [comment]
@sromku, thank you to add me to your app.
Tried with it and it works. Looks like the issues is around my app and (or) my role in the app. I'll have a look and come back to this ticket.

**Comment by sromku** [comment]
@vedi ok, big thanks for an update!! if you find out what was an issue, please update. it is very important to figure out what causes this misbehaviour. Thanks!

**Comment by vedi** [comment]
@sromku, the solution was stupidly easy. I have not checked this app id for long time, and looks like somebody changed it to other app, which is not available to me. I changed app id, and it works in my project as well. Thank you for patience and your time.

**Comment by sromku** [comment]
@vedi in any case, even if put wrong values, I would expect for error message or even exception. It is interesting case, and I will check it. Thanks for sharing and this is very important ticket. 
Have a good weekend!
