### ISSUE TITLE
Attrs file contains FloatingActionButton attrs

### ISSUE THREAD

**Issue by aminelaadhari** [sromku/android-simple-facebook#330]
The attires file contains attrs form FloatingActionButton, I don't think that is intended and should be removed because it causes the compilation to fail when FloatingActionButton is really used.

Thanks

**Comment by sromku** [comment]
@aminelaadhari Right! Not cool :(. Updating.

**Comment by sromku** [comment]
Fixed. All resources shouldn't be in this lib. Uploaded to maven. Please use **4.0.3**
``` gradle
dependencies {
    compile 'com.sromku:simple-fb:4.0.3'
}
```
Much thanks for catching this!

**Comment by aminelaadhari** [comment]
thanks !
