### ISSUE TITLE
method to get the new AccessToken class

### ISSUE THREAD

**Issue by raylee4204** [sromku/android-simple-facebook#334]
Before the new update, there used to be a method to get direct access to the AccessToken through Session class.

Now that there's no Session class anymore, there's only a method that returns AccessToken as String.

But it'd be great to receive the actual AccessToken object, which includes expire date and permissions

**Comment by sromku** [comment]
@raylee4204 good point, fixed and you can use latest version: 4.0.5.
Latest changes in this version: [here](https://www.facebook.com/permalink.php?story_fbid=1606981396224942&id=1501124800143936)

Best,
Roman
