### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by Reisto** [sromku/android-simple-facebook#336]
Hey i want to login to facebook with my app and get some data from the user.
But when i try it like in the sample project it fails and i can't find out why.

I've created a question on stackoverflow for this problem and i thought maybe it could be solved here too. Here is the link to the stackoverflow question with all my code and screenshots:

[Stackoverflow-Link](http://stackoverflow.com/questions/31098374/login-to-facebook-using-android-simple-facebook-from-sromku-fails)

**Comment by sromku** [comment]
@Reisto Few questions to verify the issue:

1. If you take the sample as is and update the values as it explained here: 
https://github.com/sromku/android-simple-facebook/wiki/Sample-App, do you crash?

2. Ensure that you added these lines in your own implementation: 

   ``` java
   @Override
   public void onResume() {
       super.onResume();
       mSimpleFacebook = SimpleFacebook.getInstance(this);
   }
   ```

   And:
   ``` java
   @Override
   protected void onActivityResult(int requestCode, int resultCode, Intent data) {
       mSimpleFacebook.onActivityResult(requestCode, resultCode, data); 
       super.onActivityResult(requestCode, resultCode, data);
   } 
   ```
Check it here: https://github.com/sromku/android-simple-facebook/wiki/Configuration

**Comment by Reisto** [comment]
Thanks for your quick response!

to 1.:
I followed the steps 1, 2 and 3 and it works perfectly fine. But i wasn't able to follow step 4 because i don't know what's my namespace?!

to 2.:
I also added this lines of code in my MainActivity but when i hit the login button it chrashes

**Comment by sromku** [comment]
1. The app namespace is located below app secret in the app dashboard settings. You can see it in this [screenshot](https://github.com/sromku/android-simple-facebook/wiki/images/sample-app-dashboard.png).

2. Please check the when you use `SimpleFacebook.getIntance(Activity)`, you pass the actual `Activity` inside the getInstance(..) method. 

Let me know if you still have an issue.

**Comment by Reisto** [comment]
Yes i know where to put it in the dashboard but i don't know what's the namespace of my app.

Im calling it in the MainActivity with `mSimpleFacebook = SimpleFacebook.getInstance(this);`

**Comment by sromku** [comment]
The namespace is something that you create and fill in the field of namespace in app dashboard. Then you can use it where it is necessary. In general, namespace is needed when you want to publish open graph stories. If this feature isn't needed, then you can skip this option.

Do you have the same crash as before? Can you please put the stacktrace that you get here. Thanks.

**Comment by Reisto** [comment]
I need to store some informations of the users managed groups so i don't think i need a namespace?!

![error](https://cloud.githubusercontent.com/assets/13086146/8396553/53678f60-1dab-11e5-9b15-d928171554b4.JPG)

**Comment by Reisto** [comment]
Maybe my code can help to find the issue:

**MainActivity:**

    package mc.fhooe.at.testapp;

    import android.content.Intent;
    import android.support.v7.app.ActionBarActivity;
    import android.os.Bundle;
    import android.util.Log;
    import android.view.Menu;
    import android.view.MenuItem;
    import android.view.View;
    import android.widget.Button;
    import android.widget.TextView;

    import com.sromku.simple.fb.Permission;
    import com.sromku.simple.fb.SimpleFacebook;
    import com.sromku.simple.fb.SimpleFacebookConfiguration;
    import com.sromku.simple.fb.entities.Account;
    import com.sromku.simple.fb.entities.Profile;
    import com.sromku.simple.fb.listeners.OnAccountsListener;
    import com.sromku.simple.fb.listeners.OnLoginListener;
    import com.sromku.simple.fb.listeners.OnProfileListener;

    import java.util.List;


    public class MainActivity extends ActionBarActivity {

    private String mAppID;
    private SimpleFacebook mSimpleFacebook;
    private TextView mTVName;
    private TextView mTVGroups;
    private TextView mTVId;
    private Button mLoginButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mSimpleFacebook = SimpleFacebook.getInstance(this);

        mAppID = getString(R.string.app_id);
        mTVName = (TextView)findViewById(R.id.tv_name);
        mTVId = (TextView)findViewById(R.id.tv_id);
        mTVGroups = (TextView)findViewById(R.id.tv_groups);
        mLoginButton = (Button)findViewById(R.id.b_login);

        Permission[] permissions = new Permission[] {
                Permission.PUBLIC_PROFILE,
                Permission.MANAGE_PAGES,
        };

        SimpleFacebookConfiguration configuration = new SimpleFacebookConfiguration.Builder()
                .setAppId(mAppID)
                .setPermissions(permissions)
                .build();

        SimpleFacebook.setConfiguration(configuration);

        setLogin();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mSimpleFacebook = SimpleFacebook.getInstance(this);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        mSimpleFacebook.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }

    protected void getData() {
        OnProfileListener onProfileListener = new OnProfileListener() {
            @Override
            public void onComplete(Profile profile) {
                Log.i("Profile", "My profile id = " + profile.getId());

                mTVId.setText(profile.getId());
                mTVName.setText(profile.getName());
            }
        };

        Profile.Properties prop = new Profile.Properties.Builder()
                .add(Profile.Properties.ID)
                .add(Profile.Properties.NAME)
                .build();

        mSimpleFacebook.getProfile(prop, onProfileListener);

        OnAccountsListener onAccountsListener = new OnAccountsListener() {
            @Override
            public void onComplete(List<Account> accounts) {
                Log.i("GET Account", "Number of accounts = " + accounts.size());

                mTVGroups.setText(accounts.size());
            }
        };

        mSimpleFacebook.getAccounts(onAccountsListener);
    }

    public void setLogin() {
        final OnLoginListener onLoginListener = new OnLoginListener() {

            @Override
            public void onLogin(String accessToken, List<Permission> acceptedPermissions,     List<Permission> declinedPermissions) {
                Log.i("FB Login", "Logged in");
                getData();
            }

            @Override
            public void onCancel() {
                // user canceled the dialog
            }

            @Override
            public void onFail(String reason) {
                Log.i("Login failed", reason);
            }

            @Override
            public void onException(Throwable throwable) {
                // exception from facebook
            }
        };

        mLoginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View arg0) {
                mSimpleFacebook.login(onLoginListener);
            }
        });
    }
    }

**build.gradle:**

    apply plugin: 'com.android.application'

    android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "mc.fhooe.at.testapp"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    }


    dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.sromku:simple-fb:4.0.4'
    compile 'com.facebook.android:facebook-android-sdk:4.2.+'
    //compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    }

**Manifest:**

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="mc.fhooe.at.testapp" >

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:label="@string/app_name" />
    </application>

    <meta-data
        android:name="com.facebook.sdk.ApplicationId"
        android:value="@string/app_id" />

    </manifest>

**Comment by sromku** [comment]
ok, just found this issue. please put the `meta-data` inside the `application` scope in the manifest.
The crash happens due to bad handling of [loadDefaultsFromMetadata](https://github.com/facebook/facebook-android-sdk/blob/master/facebook%2Fsrc%2Fcom%2Ffacebook%2FFacebookSdk.java#L564) method in facebook sdk. 

Now, I hope we are good :) 
Let me know if you have any questions.

**Comment by Reisto** [comment]
Now the login works fine thank you very much! ;)

But now i've got problems with getting the accounts of my facebook page although i'vh set the manage_page permission?

**Comment by sromku** [comment]
Enjoy :)

The `manage_page` permission is the correct one. But for getting accounts you need to accept this permission from login dialog. Since this permission is from `publish` family permissions (https://developers.facebook.com/docs/facebook-login/permissions/v2.3#reference-manage_pages) the login dialog with this permission can be triggered in 2 different ways:

1. In your `SimpleFacebookConfiguration` you ask that all permissions that you defined will be asked all at once. Which means, the read permissions will be asked first and moment after, the publish permissions will be asked. This is the method: `setAskForAllPermissionsAtOnce(false)`. You can see all possible configurations here: https://github.com/sromku/android-simple-facebook/wiki/Configuration-options. Just note that facebook don't like the idea of asking all permissions at once and they might decline your app if you submit for review. 

2. The other options which is far better and compliant with facebook policies is requesting new permissions when needed. Use this method and ask for `manage_page`: https://github.com/sromku/android-simple-facebook/wiki/Request-new-permissions

**Comment by Reisto** [comment]
But if it's from the publish family i need to set the namespace or am I wrong with this?
And if so how can i set an namespace for my app?

**Comment by sromku** [comment]
mmm, I am pretty sure that you don't need namespace for requesting any permission. But if I'm wrong to set a namespace for your app you just need to put any string you want under app settings dashboard in the Namespace text box and then use `.setNamespace("string_that_you_invented")` in `SimpleFacebookConfiguration` builder.

**Comment by Reisto** [comment]
I don't get it :/

I've tried to `setAskForAllPermissionsAtOnce(true)` but it didn't work. I get back an `List<Accounts`-object with size 0 but I've got one group with my FB-account, so I thought i might have forgotten some permissions and tried to set the same permissions I've granted in the example app because there i get my group but it didn't work! When i try to set the text of a TextView with my number of groups like ` mTVGroups.setText(accounts.size());` it chrashes instead of writing 0 to the textView as i would expect.

Here the error message:
![erroraccount](https://cloud.githubusercontent.com/assets/13086146/8397290/1c478226-1dc7-11e5-809d-8a58c6661eb6.JPG)

**Comment by sromku** [comment]
In your `onComplete(List<Account> accounts)` you use:
``` java
mTVGroups.setText(accounts.size());
```

When you set text and put integer as parameter, android consider this integer as string resource id and not as string input. This method [TextView#setText(int res)](http://developer.android.com/reference/android/widget/TextView.html#setText(int))

In your case you need the size to be a string. So there is a plenty options to do this. One of them is like this:
``` java
mTVGroups.setText(String.valueOf(accounts.size()));
```
