### ISSUE TITLE
Can i get the events of a page?

### ISSUE THREAD

**Issue by Reisto** [sromku/android-simple-facebook#337]
I want to get the events of the managed page of an user.
With the facebook graph API explorer i only need the pageID and "/events" to get the events.
But there is no such function like `getEvents` for a page-object. 
Can i get the events on another way?

**Comment by sromku** [comment]
Sure you can. Just put the page id in the place of `entityId` param and you get the events of page. It's explained here: https://github.com/sromku/android-simple-facebook/wiki/Get-events
Best, Roman

**Comment by Reisto** [comment]
thx you are awesome! ;)

**Comment by sromku** [comment]
:)
