### ISSUE TITLE
app:unspecified

### ISSUE THREAD

**Issue by mwoitter** [sromku/android-simple-facebook#338]
Hi all!
I would like to add simple-fb and facebook with maven. I take the last release of simple-fb with maven and I have this return in gradle console:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[22,23).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
         https://jcenter.bintray.com/com/android/support/support-v4/
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         file:/E:/Android Studio/Android/sdk1/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml
         file:/E:/Android Studio/Android/sdk1/extras/google/m2repository/com/android/support/support-v4/maven-metadata.xml
         file:/E:/Android Studio/Android/sdk1/extras/google/m2repository/com/android/support/support-v4/
     Required by:
         Capt'Us:app:unspecified > com.sromku:simple-fb:4.0.1 > com.facebook.android:facebook-android-sdk:4.2.0

Have you an idea for me?

Thanks a lot!

**Comment by sromku** [comment]
Please install support library from SDK manager.
```
Android Studio -> Tools -> Android -> SDK Manager -> scroll to Extras -> Check and install Android Support Library. 
```
Facebook lib has dependency on this support lib. Since this lib has dependency on facebook lib, you get failed.

**Comment by mwoitter** [comment]
Thanks, it works!
Simple-fb is very powerful and helps a lot!

**Comment by sromku** [comment]
Glad to help :)
