### ISSUE TITLE
getFriends return empty List

### ISSUE THREAD

**Issue by mwoitter** [sromku/android-simple-facebook#339]
Hi everybody!

I met a mistake (maybe)...

mSimpleFacebook.getFriends(onFriendsListener); return "Number of friends = 0".
But this morning one friends was log with her FB account to my application so I should have "Number of friends = 1".

This is my code, similar as the wiki:

         private SimpleFacebook mSimpleFacebook;
        @Override
        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);

        mSimpleFacebook = SimpleFacebook.getInstance(this);

        OnFriendsListener onFriendsListener = new OnFriendsListener() {
            @Override
            public void onComplete(List<Profile> friends) {
                Log.i(TAG, "Number of friends = " + friends.size());
            }

    /*
     * You can override other methods here:
     * onThinking(), onFail(String reason), onException(Throwable throwable)
     */
        };

        mSimpleFacebook.getFriends(onFriendsListener);
    }

    @Override
    public void onResume() {
        super.onResume();
        mSimpleFacebook = SimpleFacebook.getInstance(this);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        mSimpleFacebook.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }

**Comment by sromku** [comment]
@mwoitter what was the issue eventually?

**Comment by mwoitter** [comment]
I'm a dumb... I have updated permissions but no logout others users and I. So friends informations was unavailable... Sorry.
