### ISSUE TITLE
'Login with Facebook' button

### ISSUE THREAD

**Issue by xsorifc28** [sromku/android-simple-facebook#342]
Is there a way to adopt the default login button style, or login using that button?

I ran into a couple issues while attempting to implement the facebook sdk native login button.

**Comment by sromku** [comment]
@xsorifc28 Please elaborate more. I can't understand what you mean. And what is the issue. If you want facebook button look and feel, then use `LoginButton`. If you want to make login and control the flow, then use this lib or facebook-sdk directly. Styling views is not supported by this lib.

**Comment by xsorifc28** [comment]
Can you provide an example of how to use the LoginButton?

The issue is that permission dialog comes up twice. 

First time it says "will receive the following info: your public profile"  

(Native facebook login button permission request?)

Second time it says "will receive the following info: email, hometown, photos"

(The permissions that I requested when configuring SimpleFacebook instance.)

Here's what I've done:

	FacebookSdk.sdkInitialize(getApplicationContext());
	setContentView(R.layout.activity_main);
	mLoginButton = (Button) findViewById(R.id.facebookLogin);

        OnLoginListener onLoginListener = new OnLoginListener() {

			@Override
			public void onFail(String reason) {
				Log.w(TAG, "Failed to login");
			}

			@Override
			public void onException(Throwable throwable) {
				Log.e(TAG, "Bad thing happened", throwable);
			}

			@Override
			public void onLogin(String accessToken, List<Permission> acceptedPermissions, List<Permission> declinedPermissions) {
				// change the state of the button or do whatever you want
				Log.i(TAG, SimpleFacebook.getInstance().getAccessToken().toString());
			}

			@Override
			public void onCancel() {
				Log.i(TAG,"Login Cancelled");
			}

		};

		mLoginButton.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View arg0) {
				mSimpleFacebook.login(onLoginListener);

			}
		});

How should I request the permissions or implement the native button style so that there is only one "Okay" dialog?

Thank you for your help!

**Comment by sromku** [comment]
What is the type of `R.id.facebookLogin`? If it is the `LoginButton` of facebook, then you can see such behaviour because they have 2 on click listeners inside the implementation. And there is no neat way to override it. As I mentioned, this lib will work with any custom view, but don't combine there view that already make the functionality with this lib.

**Comment by xsorifc28** [comment]
Seems that way. I attempted to override it, but it did not work. The only solution I can think of is using an ImageButton with a custom "Login with Facebok" feel.

Thanks again for the help!

**Comment by sromku** [comment]
Yep, it looks like the only way.
Best, Roman
