### ISSUE TITLE
Can't get hometown page ID via profile

### ISSUE THREAD

**Issue by xsorifc28** [sromku/android-simple-facebook#343]
Used to be able to get the hometown page id via get profile. Now this method seems to be returning just the name of the hometown.

Is there another way to get the ID field?  I see that it is still being stored in the profile object, just can't access it.

**Comment by sromku** [comment]
@xsorifc28 right, fixed on https://github.com/sromku/android-simple-facebook/tree/dev branch. Will be merged to master soon.

**Comment by xsorifc28** [comment]
You're awesome!
