### ISSUE TITLE
crash when checking for isLogin()

### ISSUE THREAD

**Issue by azizimusa** [sromku/android-simple-facebook#346]
I got an error like this 
"Attempt to invoke virtual method 'boolean com.sromku.simple.fb.SimpleFacebook.isLogin()' on a null object reference"

FYI, the login is success, but doing checking for isLogin(), the app crash.

**Comment by azizimusa** [comment]
i figure it out. I need to reference `this` inside SimpleFacebook.getInstance()

        mSimpleFacebook = SimpleFacebook.getInstance(this);

**Comment by sromku** [comment]
:+1:
