### ISSUE TITLE
Login details not found like email ,username dob of user 

### ISSUE THREAD

**Issue by sdevani92** [sromku/android-simple-facebook#355]
Hello,
This is very nice library and now it's have android studio support thanks for that.
now i come to issue  i am use this library for login using facebook and get user email and basic details 
using this i get login in but didn't get the user full profile i didn't get mail address of user i am using API version 2.4 but i am try in old API 2.2 or API version 2.1 it is working. is this issue with facebook or in library give me some suggestion Thank you.   i didn't get any error it is come in onComplete  method of  onProfileListener . it is also give me my facebook profile id.

**Comment by sdevani92** [comment]
ok it is done by 
    Profile.Properties properties = new Profile.Properties.Builder()

                    .add(Profile.Properties.NAME)
                    .add(Profile.Properties.EMAIL)
                    .build();


add properties at the time of call onProfileListener.  on graph api there is some change 
Fewer default fields for faster performance: To help improve performance on mobile network connections, we've reduced the number of fields that the API returns by default. You should now use the ?fields=field1,field2 syntax to declare all the fields you want the API to return.

**Comment by mahesh825mahi** [comment]
Where i need to add this code

**Comment by sdevani92** [comment]
http://prntscr.com/8jjyj2  
check this

**Comment by mahesh825mahi** [comment]
Thanks Bro now it's working fine..

**Comment by mahesh825mahi** [comment]
Hi i used the code like above u gave. But it returning null value only for Email.
