### ISSUE TITLE
[IMP] Needs update to 4.5+

### ISSUE THREAD

**Issue by singhdd93** [sromku/android-simple-facebook#361]
Unable to send Messages, App Invites etc. 
Also "user_groups" have been changed.

**Comment by sromku** [comment]
@singhdd93 right. Will update this lib soon to match latest graph version.

**Comment by singhdd93** [comment]
@sromku thanks a lot. I really love this lib and use it a lot.

**Comment by marsicdev** [comment]
+1

**Comment by vedi** [comment]
+1

**Comment by gibbz-one** [comment]
+1

**Comment by sromku** [comment]
@singhdd93 @marsicdev @gibbz-one @vedi  pull request to master with all needed changed: https://github.com/sromku/android-simple-facebook/pull/369
to merged if no new comments :)

Changes:

1. Updated permissions: 
 - Deprecated: `PUBLIC_PROFILE`
 - Deprecated: `USER_ACTIVITIES`
 - Deprecated: `USER_INTERESTS`
 - Deprecated: `READ_MAILBOX`
 - Deprecated: `READ_STREAM` 
 - Deprecated: `MANAGE_NOTIFICATIONS`
 - Added: `USER_MANAGED_GROUPS` (previously it was: `USER_GROUPS`)
 - Added: `READ_CUSTOM_FRIENDLISTS` (previously it was: `READ_FRIENDLISTS`)
 - Added: `USER_POSTS`
 - Added: `ADS_READ`
 - Added: `READ_AUDIENCE_NETWORK_INSIGHTS`

2. FB updated min SDK to be 15. Here, we added override to this version to be 9 as always

3. Updated docs and samples

4. New configuration option to set older graph api version

``` java
SimpleFacebookConfiguration configuration = new SimpleFacebookConfiguration.Builder()
    ...
    .setGraphVersion("v2.3")
    .build();
```

**Comment by sromku** [comment]
Updated and fixes. Thanks.

**Comment by singhdd93** [comment]
Thanks a lot.
