### ISSUE TITLE
Login with facebook

### ISSUE THREAD

**Issue by Wyllyam** [sromku/android-simple-facebook#364]
Hi friend.

I'm trying to log in with facebook using your library, but am finding this error:

Invalid Scopes: user_groups. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions}

My permissions that were I enabled:

  Permission[] permissions = new Permission[]{
                Permission.PUBLIC_PROFILE,
                Permission.EMAIL,
                Permission.USER_EVENTS,
                Permission.USER_ACTIONS_MUSIC,
                Permission.USER_FRIENDS,
                Permission.USER_GAMES_ACTIVITY,
                Permission.USER_BIRTHDAY,
                Permission.USER_GROUPS,
                Permission.PUBLISH_ACTION,
                Permission.USER_LIKES,
                Permission.USER_STATUS};

Can you help me?
Thank you!

**Comment by Wyllyam** [comment]
I managed removing the Permission.USER_GROUPS line of permissions. I do not know what might be going on, but to remove that line with me worked.

**Comment by singhdd93** [comment]
That permission has been changed in GraphAPI 2.4 . The only option is to wait for update of Lib, or dont use the things which aren't working (sending message, invites) .These were few I tested which didn't work
