### ISSUE TITLE
Getting a user's 'hometown' or 'location'

### ISSUE THREAD

**Issue by xsorifc28** [sromku/android-simple-facebook#375]
By default, the Graph API returns `id` and `name` when getting a user's hometown or location.

For example, `me?fields=location,hometown` returns 

    {
      "location": {
        "id": "xxxxxxxxxxxxx",
        "name": "xx, xx"
      },
      "hometown": {
        "id": "xxxxxxxxxxxxx",
        "name": "xx, xx"
      },
      "id": "xxxxxxxxxxxxx"
    }

When getting a users profile via SimpleFacebook, the Location field is not corretcly populated since the `Location` class does not contain id or name. `Profile.getLocation().getX() is therefore null.

The same issue does not happen with `Hometown`, since it was recently updated to extend the `IdName` class. Instead, I have to manually get the page via `Profile.getHometown().getId()`.

My suggestion is to check if the profile properties contains `Properties.Location` and `Properties.Hometown` and retrieve the actual `Location` of the respective pages (via their id).

Alternatively, a `CurrentLocation` class can be created, which would be the same as `Hometown` and then manually perform another `Get` request to grab the user's current location information. 

I wasn't sure how to implement the first suggestion!

**Comment by sromku** [comment]
@xsorifc28 I think we can change the `Location` to extend `IdName`. This will provide the `id` and `name` for this entity and should resolve this kind of response. WDYT?

**Comment by xsorifc28** [comment]
That would solve the issue, but still would require manually getting a place page for location/hometown. 

It would be easy to write a GetPlace action so that can be implemented to make a smoother transition to getting places. 

Best option would be to retrieve these pages if they were requested in the profile request by first having both classes extend IdName with a Location field.

**Comment by sromku** [comment]
I am not sure I understood you about writing GetPlace action and smoother transition.

**Comment by xsorifc28** [comment]
The fix you applied should now get the id and name for the location, but will not populate the city/country/state/latitude/longitude etc. when using the GetProfile action. 

I was trying to suggest a way to populate these fields with GetProfile rather than making another request.

**Comment by xsorifc28** [comment]
Update: see pull request #383
