### ISSUE TITLE
Comments CreateTime is Wrong 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [sromku/android-simple-facebook#377]
I just write this line 
SimpleFacebook.getInstance(getActivity()).getComments(postId,onCommentsListener)
and return Comments data all correct except CreateTime all around 17 January 1970 
Am I use older version so I need to update library  ??
-----------------------------------------------------
I tracked the response returned from Facebook and I found that the value is wrong from Facebook server 
but when I try same url in browser I get Correct result 
I'm using facebook sdk "3.19.0"  
any body have workaround for this except updating SDK because I don't want to now 
@sromku  you can close this issue because it is not Simple Facebook SDK issue

**Comment by sromku** [comment]
thanks for update @mahmoud-elnaggar
