### ISSUE TITLE
Why is minimum sdk changed?

### ISSUE THREAD

**Issue by seshuvinay** [sromku/android-simple-facebook#385]
In the new version, why is minimum sdk version changed to 15?

**Comment by sromku** [comment]
@seshuvinay Good question. The reason for this is that facebook on their side, decided to change their min SDK to 15. Also, gradle version 1.2.3 that was also updated, fails builds if your min SDK is lower then the min SDKs of libraries you use. Please see this issue that was opened on their side: https://github.com/facebook/facebook-android-sdk/pull/444

If you still want to work with lower version in your app, then add to your app manifest `overrideLibrary` attribute. Like this:
```
<uses-sdk android:minSdkVersion="9"
          tools:overrideLibrary=“com.facebook.android, <libs-here> ”/>
```

**Comment by seshuvinay** [comment]
Oh. Alright. Thanks.
