### ISSUE TITLE
cannot use Profile.Properties.WORK

### ISSUE THREAD

**Issue by rghwang** [sromku/android-simple-facebook#388]
If I call getProfile with properties.WORK, I get an exception like this.

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 762 path $.work[0].position

**Comment by rghwang** [comment]
Work's position data is an object "position":{"id":"250335031707257","name":"Co-Founder"} but Work.java's mPosition is String type.

**Comment by wiznuq** [comment]
Same Problem here
