### ISSUE TITLE
Error:Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory

### ISSUE THREAD

**Issue by wangbourne** [sromku/android-simple-facebook#405]
Compile error.

I think the solution could be:  (I verified it here)

gradle version from
classpath 'com.github.dcendents:android-maven-plugin:1.2'
to
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'

**Comment by voghDev** [comment]
In my case this line worked, together with:

_gradle/gradle-wrapper.properties:_

    distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

and with

_build.gradle:_

    dependencies{
        classpath 'com.android.tools.build:gradle:2.0.0'
        ...
    }

**Comment by wangbourne** [comment]
thanks, yes, it works now:)

**Comment by mpsandhu** [comment]
> In my case this line worked, together with:
> 
> _gradle/gradle-wrapper.properties:_
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip
> ```
> and with
> 
> _build.gradle:_
> 
> ```
> dependencies{
>     classpath 'com.android.tools.build:gradle:2.0.0'
>     ...
> }
> ```

It works like a charm
