### ISSUE TITLE
Configuration Error After Upgrade Firebase Version

### ISSUE THREAD

**Issue by budasuyasa** [sromku/android-simple-facebook#442]
Hello guys, i got this error after upgrade to firebase 9.4.0

`java.lang.NoSuchMethodError: No static method getAPIVersion()Ljava/lang/String; in class Lcom/facebook/internal/ServerProtocol; or its super classes (declaration of 'com.facebook.internal.ServerProtocol'`

This error triggered by `SimpleFacebook.setConfiguration(configuration);`

I hope you guys can help me.

**Comment by kanch1609** [comment]
just remove Facebook android sdk library from module dependencies, as it is leading to duplicated dependencies

**Comment by budasuyasa** [comment]
Thank you. Solved now.

**Comment by ArunkumarKAndanshetti** [comment]
What problem I'm facing right now : please help me.......
java.lang.NoSuchMethodError: No static method getAPIVersion()Ljava/lang/String; in class Lcom/facebook/internal/ServerProtocol; or its super classes (declaration of 'com.facebook.internal.ServerProtocol' appears in /data/data/files/instant-run/dex/slice-com.facebook.android-facebook-android-sdk-4.20.0_2df9bd60de02704e486702ea6f1502ee3426b9c4-classes.dex)

**Comment by ArunkumarKAndanshetti** [comment]
My dependency....
compile project(':library_pinnlistivew')
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.soundcloud.android:android-crop:1.0.1@aar'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.20.0'
    compile 'com.sromku:simple-fb:4.1.1'
    compile files('libs/android-query.0.26.7.jar')
    compile files('libs/apache-mime4j-core-0.7.2.jar')
    compile files('libs/httpclient-4.3.5.jar')
    compile files('libs/httpcore-4.3.2.jar')
    compile files('libs/httpmime-4.3.5.jar')
    compile files('libs/splunk-mint-4.0.8.jar')
    compile files('libs/gcm.jar')


Sir please help me....

**Comment by ArunkumarKAndanshetti** [comment]
project gradle : classpath 'com.android.tools.build:gradle:2.1.3'
