### ISSUE TITLE
Android Studio Support

### ISSUE THREAD

**Issue by WikiBruce** [sromku/android-simple-facebook#56]
Great work. Thanks a lot for the effort. Is there any chance of you adding instructions to configure Android Studio to make use of the library?

**Comment by eoinzy** [comment]
FYI, I got this working by putting the simple.facebook-2.2.jar in my /libs folder and referencing it in my build.gradle like so:
    compile files('libs/simple.facebook-2.2.jar')

I then simply referenced an older version of Facebook from Gradle like so:
    compile 'com.facebook.android:facebook-android-sdk:3.23.1'

I know its an older version of the FB SDK, but it seems to work, for now.
