### ISSUE TITLE
Sample application runs well in android studio, but my application crashes when I call login().

### ISSUE THREAD

**Issue by bigyanthapa** [sromku/android-simple-facebook#69]
Hi Sromku, Thank you for your great job. I have working around facebook sdk from couple of weeks. But was only successful to integrate the functions in bits in my app. As I found this api, I felt some relief. I setup the project as described. Now the sample app runs well when I run in android studio, but my app crashes when I call login method when a button is clicked. I tried to figure out this on my own but couldn't find what was wrong. So, please help me out to sort this. 
Thank you again. It would be great if you could reply fast.

**Comment by rohanphatak** [comment]
can u upload your simplefacebook class?
it will be nice to understand. I dint find it in ur github code. Thabk you.
