### ISSUE TITLE
Is it possible to publish a comment on a page?

### ISSUE THREAD

**Issue by juliocbcotta** [sromku/android-simple-facebook#89]
Hi, I would like to know if it is possible to use this lib to publish a page outside facebook? Just like the social plugin does https://developers.facebook.com/docs/plugins/comments/

Thanks.

**Comment by MarekKott** [comment]
@sromku 
Would you like to tell me the function for publishing a comment,  is completed?
I have a problem when we try to do comment/like on a post.

The response is following:
"Could not construct request body"
